version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=BarApp
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3369:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      springboot-mysql:

  springboot-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/BarApp?autoReconnect=true&useSSL=false
    networks:
      springboot-mysql:

volumes:
  db-data:
networks:
  springboot-mysql:
